name: New Feature Request
description: Suggest a new feature for the project
title: "[Feature]: "

labels: ["feature", "enhancement"]

body:
  - type: input
    id: name
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Seritha Taweewattana
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: request-type
    attributes:
      label: Type of request
      description: Select the type of your request
      options:
        - New Feature
        - Improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: What is the OS which you want to suggest?
      description: Select your operating system
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: suggestion-details
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
      placeholder: Feature details!
    validations:
      required: true
